import { useRef } from 'react';
import { motion } from 'motion/react';
import { 
  FileDown, 
  AlertTriangle, 
  TrendingUp, 
  Target, 
  Info,
  ChevronDown,
  ChevronUp,
  CheckCircle,
  XCircle,
  Lightbulb
} from 'lucide-react';
import { 
  Radar, 
  RadarChart, 
  PolarGrid, 
  PolarAngleAxis, 
  ResponsiveContainer 
} from 'recharts';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { Section } from '../services/geminiService';
import { ImpactAnalysis, OverallScorecard } from '../services/claudeService';
import { useState } from 'react';

interface DashboardProps {
  country: string;
  summary: OverallScorecard;
  sections: Section[];
  analyses: Record<string, ImpactAnalysis>;
}

export default function Dashboard({ country, summary, sections, analyses }: DashboardProps) {
  const reportRef = useRef<HTMLDivElement>(null);
  const [expandedSection, setExpandedSection] = useState<string | null>(null);

  const radarData = [
    { subject: 'Cultural Fit', A: summary.overallScores.cultural, fullMark: 100 },
    { subject: 'Economic', A: summary.overallScores.economic, fullMark: 100 },
    { subject: 'Legal', A: summary.overallScores.legal, fullMark: 100 },
    { subject: 'Human Rights', A: summary.overallScores.humanRights, fullMark: 100 },
    { subject: 'Future-Proof', A: summary.overallScores.future, fullMark: 100 },
  ];

  const exportToPDF = async () => {
    if (!reportRef.current) return;
    
    const canvas = await html2canvas(reportRef.current, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#F9FAFB'
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);

    // Attribution footer
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.setFontSize(7);
    pdf.setTextColor(180, 180, 180);
    pdf.text(
      `Generated by PolicyLens AI · Built by Ahmad Rafi (Insights Bangladesh · NagorikBD · Talk Bangladesh) · Data: World Bank, TI Index, Hofstede, UN SDG`,
      pdfWidth / 2,
      pageHeight - 4,
      { align: 'center' }
    );

    pdf.save(`PolicyLens-Report-${country}-${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-emerald-600 bg-emerald-50';
    if (score >= 50) return 'text-amber-600 bg-amber-50';
    return 'text-red-600 bg-red-50';
  };

  const getBarColor = (score: number) => {
    if (score >= 80) return 'bg-emerald-500';
    if (score >= 50) return 'bg-amber-500';
    return 'bg-red-500';
  };

  return (
    <div className="w-full max-w-5xl mx-auto space-y-12 pb-32">
      {/* Export Header */}
      <div className="flex justify-end">
        <button
          onClick={exportToPDF}
          className="flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-xl font-semibold hover:bg-slate-800 transition-all shadow-lg shadow-slate-200"
        >
          <FileDown className="w-4 h-4" />
          Export Full Report
        </button>
      </div>

      <div ref={reportRef} className="space-y-12 p-8 sm:p-12 bg-[#F9FAFB] rounded-[40px] border border-slate-100 shadow-sm overflow-hidden">
        {/* Executive Header */}
        <header className="border-b border-slate-200 pb-12">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-10">
            <div>
              <span className="text-[10px] font-bold uppercase tracking-[0.3em] text-slate-400 block mb-3">Policy Audit Report</span>
              <h1 className="text-4xl font-bold text-slate-900 tracking-tight">Strategic Assessment: {country}</h1>
            </div>
            <div className="flex items-center gap-3">
              <div className="px-4 py-2 bg-white rounded-full border border-slate-100 shadow-sm flex items-center gap-2">
                <Info className="w-4 h-4 text-slate-400" />
                <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Confidential AI Analysis</span>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
            <div className="lg:col-span-2 space-y-6">
              <h2 className="text-sm font-bold uppercase tracking-widest text-slate-400">Executive Summary</h2>
              <div className="text-slate-600 leading-relaxed space-y-4 text-lg serif">
                {summary.summary.split('\n').map((para, i) => (
                  <p key={i}>{para}</p>
                ))}
              </div>
            </div>
            
            <div className="space-y-6">
              <div className="p-6 bg-red-50 rounded-3xl border border-red-100">
                <div className="flex items-center gap-2 mb-3 text-red-600">
                  <AlertTriangle className="w-5 h-5" />
                  <span className="text-xs font-bold uppercase tracking-wider">Primary Systemic Risk</span>
                </div>
                <p className="text-sm text-red-900 font-medium leading-relaxed">{summary.keyRisk}</p>
              </div>
              <div className="p-6 bg-emerald-50 rounded-3xl border border-emerald-100">
                <div className="flex items-center gap-2 mb-3 text-emerald-600">
                  <TrendingUp className="w-5 h-5" />
                  <span className="text-xs font-bold uppercase tracking-wider">Core Competitive Advantage</span>
                </div>
                <p className="text-sm text-emerald-900 font-medium leading-relaxed">{summary.principalAdvantage}</p>
              </div>
            </div>
          </div>
        </header>

        {/* Global Scorecard */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center py-12 border-b border-slate-200">
          <div className="space-y-8">
            <h2 className="text-sm font-bold uppercase tracking-widest text-slate-400">Policy Performance Matrix</h2>
            <div className="grid grid-cols-1 gap-6">
              {radarData.map((item) => (
                <div key={item.subject} className="space-y-2">
                  <div className="flex justify-between items-end">
                    <span className="text-sm font-semibold text-slate-700">{item.subject}</span>
                    <span className={`text-xs font-bold px-2 py-1 rounded-md ${getScoreColor(item.A)}`}>
                      {item.A}/100
                    </span>
                  </div>
                  <div
                    className="h-2 w-full bg-slate-200 rounded-full overflow-hidden"
                    role="progressbar"
                    aria-valuenow={item.A}
                    aria-valuemin={0}
                    aria-valuemax={100}
                    aria-label={`${item.subject}: ${item.A} out of 100`}
                  >
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${item.A}%` }}
                      transition={{ duration: 1, ease: "easeOut" }}
                      className={`h-full ${getBarColor(item.A)}`}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
          
          <div className="h-[340px] sm:h-[400px] w-full max-w-[340px] sm:max-w-none mx-auto flex items-center justify-center bg-white rounded-3xl border border-slate-100 shadow-sm p-4">
             <ResponsiveContainer width="100%" height="100%">
              <RadarChart cx="50%" cy="50%" outerRadius="80%" data={radarData}>
                <PolarGrid stroke="#E2E8F0" />
                <PolarAngleAxis dataKey="subject" tick={{ fill: '#64748B', fontSize: 10, fontWeight: 700 }} />
                <Radar
                  name="Policy"
                  dataKey="A"
                  stroke="#0F172A"
                  fill="#0F172A"
                  fillOpacity={0.1}
                />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </section>

        {/* Detailed Section Breakdown */}
        <section className="space-y-8 pt-12">
          <div className="flex items-center gap-3">
            <Target className="w-5 h-5 text-slate-900" />
            <h2 className="text-sm font-bold uppercase tracking-widest text-slate-400">Detailed Section Insights</h2>
          </div>
          
          <div className="space-y-4">
            {sections.map((section) => {
              const analysis = analyses[section.id];
              if (!analysis) return null;
              const isExpanded = expandedSection === section.id;

              return (
                <div key={section.id} className="bg-white rounded-2xl border border-slate-200 overflow-hidden transition-all">
                  <button 
                    onClick={() => setExpandedSection(isExpanded ? null : section.id)}
                    className="w-full flex items-center justify-between p-6 text-left hover:bg-slate-50 transition-colors"
                  >
                    <div className="flex items-center gap-4">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${getScoreColor(Object.values(analysis.scores).reduce((a, b) => a + b, 0) / 5)}`}>
                        {Math.round(Object.values(analysis.scores).reduce((a, b) => a + b, 0) / 5)}
                      </div>
                      <div>
                        <h4 className="text-sm font-bold text-slate-900 tracking-tight">{section.title}</h4>
                        <p className="text-xs text-slate-400 font-medium">Article {section.id}</p>
                      </div>
                    </div>
                    {isExpanded ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
                  </button>

                  {isExpanded && (
                    <motion.div 
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="p-8 border-t border-slate-100 bg-white"
                    >
                      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
                        <div className="space-y-4">
                          <h5 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Dimension Analysis</h5>
                          {Object.entries(analysis.scores).map(([key, val]) => (
                            <div key={key} className="flex items-center justify-between">
                              <span className="text-xs text-slate-600 capitalize">{key.replace(/([A-Z])/g, ' $1')}</span>
                              <div className="flex items-center gap-2">
                                <div className="w-24 h-1 bg-slate-100 rounded-full overflow-hidden">
                                  <div className={`h-full ${getBarColor(val)}`} style={{ width: `${val}%` }} />
                                </div>
                                <span className="text-[10px] font-bold text-slate-900 w-6">{val}</span>
                              </div>
                            </div>
                          ))}
                        </div>
                        <div className="lg:col-span-2 space-y-4">
                          <h5 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Strategic Assessment</h5>
                          <p className="text-sm text-slate-600 leading-relaxed italic border-l-2 border-slate-100 pl-4">
                            "{analysis.culturalFit}"
                          </p>
                        </div>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                         <div className="space-y-4">
                           <div className="flex items-center gap-2 text-rose-600 mb-2">
                             <XCircle className="w-4 h-4" />
                             <h5 className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Critical Problems</h5>
                           </div>
                           <ul className="space-y-3">
                             {analysis.criticalHighlights.problems.map((p, i) => (
                               <li key={i} className="text-sm text-red-700 leading-relaxed p-3 bg-red-50/50 rounded-xl border border-red-50">{p}</li>
                             ))}
                           </ul>
                         </div>
                         <div className="space-y-4">
                           <div className="flex items-center gap-2 text-emerald-600 mb-2">
                             <CheckCircle className="w-4 h-4" />
                             <h5 className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Good Practices</h5>
                           </div>
                           <ul className="space-y-3">
                             {analysis.criticalHighlights.strongPoints.map((p, i) => (
                               <li key={i} className="text-sm text-emerald-700 leading-relaxed p-3 bg-emerald-50/50 rounded-xl border border-emerald-50">{p}</li>
                             ))}
                           </ul>
                         </div>
                         <div className="space-y-4">
                           <div className="flex items-center gap-2 text-amber-600 mb-2">
                             <Lightbulb className="w-4 h-4" />
                             <h5 className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Recommendations</h5>
                           </div>
                           <ul className="space-y-3">
                             {analysis.criticalHighlights.recommendations.map((p, i) => (
                               <li key={i} className="text-sm text-amber-700 leading-relaxed p-3 bg-amber-50/50 rounded-xl border border-amber-50">{p}</li>
                             ))}
                           </ul>
                         </div>
                      </div>
                    </motion.div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        {/* Footer Audit Mark */}
        <footer className="pt-20 text-center space-y-3">
          <div className="h-px w-20 bg-slate-200 mx-auto" />
          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.4em]">End of PolicyLens AI Report</p>
          <p className="text-[9px] text-slate-300 font-medium">
            Generated {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} · Data sources: World Bank, Transparency International, Hofstede Insights, UN SDG, REST Countries
          </p>
          <p className="text-[9px] text-slate-300">
            Built by <span className="font-semibold text-slate-400">Ahmad Rafi</span> — Founder &amp; Director, Insights Bangladesh · NagorikBD · Talk Bangladesh · AI Governance 1 Division 356 Upazilas
          </p>
        </footer>
      </div>
    </div>
  );
}
